import Head from 'next/head';
import { useEffect } from 'react';
import Header from '../components/header';
import { ExclamationIcon } from '@heroicons/react/outline';

type ErrorPageProps = {
    statusCode: number;
};

const Error = ({ statusCode }: ErrorPageProps) => {

    useEffect(() => {
        if (document) {
            document.body.classList.add('overflow-hidden', 'h-screen');
        }
    }, []);

    let errorMessage = 'Bir hata meydana geldi';

    switch (statusCode) {
        case 404: errorMessage = 'Aradığınız sayfa bulunamadı'; break;
    }

    return (
        <>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header sticky={false} />

            <main className="h-screen" id="main">

                <div className="container h-full mx-auto mt-20 flex flex-col items-center ">
                    <div className="text-center bg-violet-500 p-10 rounded-lg shadow-2xl text-gray-200 font-bold text-3xl flex flex-col items-center">
                        <ExclamationIcon className="w-3/4" />
                        <span className="my-3 text-6xl">{statusCode}</span>
                        <span className="my-3">{errorMessage}</span>
                    </div>
                </div>

            </main>

        </>
    )
}

Error.getInitialProps = ({ res, err }) => {
    const statusCode = res ? res.statusCode : err ? err.statusCode : 404
    return { statusCode }
}

export default Error