import type { NextPage } from 'next';
import Head from 'next/head';

import { randProductImage } from '../utils/sampler';
import Header from '../components/header';
import Categories from '../components/categories';
import RightBasket from '../components/rightBasket';
import RightOldOrders from '../components/rightOldOrders';
import ProductsGrid from '../components/productsGrid';
import MinPriceBar from '../components/minPriceBar';
import Carousel from '../components/corousel';

const Home: NextPage = () => {

  var slides = [], i = 0, len = 12;
  while (++i <= len) slides.push(randProductImage());

  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="">

        <MinPriceBar />

        <div className="container mx-auto my-5 overflow-hidden">
          <Carousel slidesPerView={3} spaceBetween={30} className="">
            {slides.map((slide, i) => {
              return (
                <div key={i} className="rounded-lg overflow-hidden h-60">
                  <img src={slide} className="w-full h-auto object-cover" />
                </div>
              )
            })}
          </Carousel>
        </div>

        <div className="container mx-auto grid grid-cols-10 gap-4">

          <div className="col-span-2">
            <div className="sticky top-36">
              <Categories />
            </div>
          </div>

          <div className="col-span-6">
            <ProductsGrid />
          </div>

          <div className="col-span-2">
            <div className="sticky top-36 ">
              <RightBasket />
              <RightOldOrders />
            </div>
          </div>

        </div>

      </main>

      { /* globalContext?.modal !== null && <>{globalContext?.modal}</> */}

    </>
  )
}

export default Home
